---
abstract: 'Worker Object Receiving Items From Q4M'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::mysqld: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.8.3, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Queue-Q4M-Worker
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Queue::Q4M::Worker:
    file: lib/Queue/Q4M/Worker.pm
    version: 0.03
requires:
  DBI: 0
  POSIX: 0
  Parallel::Prefork: 0
resources:
  bugtracker: https://github.com/lestrrat/Queue-Q4M-Worker/issues
  homepage: https://github.com/lestrrat/Queue-Q4M-Worker
  repository: git://github.com/lestrrat/Queue-Q4M-Worker.git
version: 0.03
x_contributors:
  - 'Daisuke Maki <lestrrat+github@gmail.com>'
